### ISSUE TITLE
If non existent frame and a refreshImg() is called, PyVexr crashes

### ISSUE THREAD

**Issue by mteillet** [mteillet/PyVexr#9]
If there is no frame // frame index in the timeLineDict and a refresh img is called, the PyVexr crashes

Easy to reproduce, load a single EXR, go out of range (next frame forward), and call an expo up or saturation tweak

Traceback (most recent call last):
  File "pyVexr_gui.py", line 109, in mouseReleaseEvent
    widget.refreshImg()
  File "pyVexr_gui.py", line 1539, in refreshImg
    shot =  self.timeLineDict[currentPos]["shot"]
KeyError: 1

**Comment by mteillet** [comment]
This appens through the mouse scrubbing :
` 
  File "pyVexr_gui.py", line 109, in mouseReleaseEvent
    widget.refreshImg()
  File "pyVexr_gui.py", line 1534, in refreshImg
    shot =  self.timeLineDict[currentPos]["shot"]
KeyError: 1
`

But also through the keypresses frame forward and backward :
` 
  File "pyVexr_gui.py", line 154, in keyPressEvent
    widget.jumpFrameForward()
  File "pyVexr_gui.py", line 1127, in jumpFrameForward
    if self.imgDict["buffer"][toCheckBuffer] != None:
IndexError: list index out of range
`

Need to fix both methods.
PyVexr is trying to find a frame outside of the timeLineDict, and therefore also out of the imgDict["buffer"].

**Comment by mteillet** [comment]
Fixed this issue in the following commit : 
[https://github.com/mteillet/PyVexr/commit/17edacff446210dd3b045907c810269f70148c22](url)

Will be part of the next release
